### ISSUE TITLE
Black and white stickers

### ISSUE THREAD

**Issue by rsethur** [evtimovi/robust_physical_perturbations#1]
First of all, Many thanks for sharing the code along with the awesome paper! Much appreciated!

**Question:** I see that noise is generated from` tf.random_uniform`. But however I see that the output as per paper is black and white alone (only two RBG numbers). Can you pls point in the code where we are restricting the output to only black and white? I was unable to find it.

Thank you in advance for the kind support.

**Comment by evtimovi** [comment]
The approach for the attack is optimization-based. So the random values are only used as initialization. Then, we optimize a loss function by updating the noise variable. See e.g. line [465](https://github.com/evtimovi/robust_physical_perturbations/blob/master/lisa-cnn-attack/utils.py#L465) in `lisa-cnn-attack/utils.py` and the lines preceding it. 

That said, the optimization solution found only black and white values, without us explicitly specifying they should be black and white.

**Comment by rsethur** [comment]
Thanks a LOT for clearing that - very interesting it is converging to black and white automatically -  wondering what the reason is.

**Comment by JinkaiZheng** [comment]
> Thanks a LOT for clearing that - very interesting it is converging to black and white automatically - wondering what the reason is.

@evtimovi  Thank you so much for your wonderful job! However, I have the same wonder about why the noise can automatically converge to black and white. Could you please give me some insights?
