### ISSUE TITLE
Will this work with complex models like Inception V3?

### ISSUE THREAD

**Issue by rsethur** [evtimovi/robust_physical_perturbations#2]
Many thanks for a wonderful paper - and open sourcing the code.
Has this been tried with more complex model like Inception? Grateful for any pointers.

**Comment by evtimovi** [comment]
Yes, the [imagenet-attack](https://github.com/evtimovi/robust_physical_perturbations/tree/master/imagenet-attack) folder has the attacks on InceptionV3

**Comment by rsethur** [comment]
many thanks for the kind response @evtimovi
