### ISSUE TITLE
Are the network parameters freezed when generating noisy images?

### ISSUE THREAD

**Issue by luotuoqingshan** [evtimovi/robust_physical_perturbations#3]
Thank you for open-sourced code and the awesome paper!
I am now working on adversarial attack and think this is a good example.
I have a question about the code. I wonder whether the params are freezed and if so in which part of the code?

**Comment by keykholt** [comment]
When doing the attack, the optimizer is only set to use the variables in the adversarial list (attack.py-line 261). The target model to attack also have a train flag (attack.py-line 206). When false, the loaded model doesn't set up its own optimizer.
